begin;

alter table public.profiles
  add column if not exists phone text,
  add column if not exists user_type text,
  add column if not exists student_number text,
  add column if not exists course text,
  add column if not exists position text,
  add column if not exists approved_by uuid references auth.users(id),
  add column if not exists approved_at timestamptz,
  add column if not exists rejection_reason text,
  add column if not exists last_login timestamptz;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role = any (array['Administrador','Supervisor','Agente','Solicitante']::text[]));
alter table public.profiles drop constraint if exists profiles_status_check;
alter table public.profiles add constraint profiles_status_check check (status = any (array['Pendente','Activo','Inactivo','Bloqueado','Recusado']::text[]));

update public.profiles
set status=case when status='Activo' then 'Activo' else 'Inactivo' end,
    user_type=case when role='Administrador' then 'ADMINISTRADOR' else 'COLABORADOR' end
where user_type is null;

alter table public.profiles alter column user_type set default 'COLABORADOR';
alter table public.profiles alter column status set default 'Pendente';

create unique index if not exists profiles_student_number_unique on public.profiles(student_number)
where student_number is not null and btrim(student_number)<>'';

alter table public.tickets add column if not exists ticket_code text;
alter table public.tickets add column if not exists assigned_department_id uuid references public.departments(id);
alter table public.tickets add column if not exists first_response_at timestamptz;
alter table public.tickets add column if not exists closed_at timestamptz;

alter table public.tickets drop constraint if exists tickets_status_check;
alter table public.tickets add constraint tickets_status_check check (
  status=any(array['Novo','Em análise','Em atendimento','Aguardando utilizador','Aguardando departamento','Escalado','Resolvido','Fechado','Reaberto','Cancelado']::text[])
);

create or replace function public.set_ticket_code()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.ticket_code is null or btrim(new.ticket_code)='' then
    new.ticket_code:='ISP-'||to_char(coalesce(new.created_at,now()),'YYYY')||'-'||lpad(new.ticket_number::text,6,'0');
  end if;
  return new;
end; $$;

drop trigger if exists trg_tickets_ticket_code on public.tickets;
create trigger trg_tickets_ticket_code before insert on public.tickets for each row execute function public.set_ticket_code();

update public.tickets set ticket_code='ISP-'||to_char(created_at,'YYYY')||'-'||lpad(ticket_number::text,6,'0') where ticket_code is null;
create unique index if not exists tickets_ticket_code_unique on public.tickets(ticket_code);

create table if not exists public.ticket_ratings(
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null unique references public.tickets(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  rating integer not null check(rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);
alter table public.ticket_ratings enable row level security;

create table if not exists public.ticket_events(
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  actor_id uuid references auth.users(id),
  event_type text not null,
  old_value text,
  new_value text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.ticket_events enable row level security;

insert into storage.buckets(id,name,public) values('ticket-attachments','ticket-attachments',false)
on conflict(id) do update set public=false;

commit;
