const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const toast=(m,ok=false)=>{const e=document.querySelector("#toast");e.textContent=m;e.className="toast show";e.style.background=ok?"#147D4B":"#30343B";setTimeout(()=>e.className="toast",3500)};
let ME=null,CATS=[];
async function boot(){if(!API.token)return renderLogin();try{ME=await API.me();CATS=await API.request("/admin/categories").catch(()=>API.request("/tickets").then(()=>[]));renderApp()}catch{localStorage.removeItem("sd_token");API.token=null;renderLogin()}}
function renderLogin(){document.querySelector("#app").innerHTML=`<div class="login"><div class="login-box"><div class="login-logo"><div class="brand-placeholder" style="margin:auto">ISPOTEC</div><h1>Service Desk</h1><p class="muted">Instituto de Formação Politécnica e de Tecnologias</p></div><form id="login"><div class="field"><label>E-mail</label><input id="email" type="email" required></div><div class="field"><label>Palavra-passe</label><input id="password" type="password" required></div><div id="loginError" class="error"></div><button class="btn yellow" style="width:100%">Iniciar sessão</button></form><p class="muted" style="font-size:12px;margin-top:18px">Demonstração: admin@ispotec.local / Admin@123</p></div></div>`;
document.querySelector("#login").onsubmit=async e=>{e.preventDefault();try{const x=await API.login(email.value,password.value);API.token=x.token;localStorage.setItem("sd_token",x.token);ME=x.user;renderApp()}catch(err){loginError.textContent=err.message}}}
function shell(content,title="Painel"){document.querySelector("#app").innerHTML=`<header class="topbar"><div class="brand"><div class="brand-placeholder">ISPOTEC</div><span>Service Desk ISPOTEC</span></div><div>${esc(ME.name)} <button class="btn secondary" onclick="logout()">Sair</button></div></header><div class="layout"><aside><nav class="nav"><a href="#" onclick="dashboard();return false">🏠 Painel</a><a href="#" onclick="newTicket();return false">➕ Novo ticket</a><a href="#" onclick="myTickets();return false">🎫 Meus tickets</a>${ME.role!=="COLABORADOR"?`<a href="#" onclick="manageTickets();return false">🛠 Gestão de tickets</a>`:""}${ME.role==="ADMIN"?`<a href="#" onclick="adminDashboard();return false">📊 Administração</a><a href="#" onclick="usersPage();return false">👥 Utilizadores</a><a href="#" onclick="categoriesPage();return false">🗂 Categorias</a><a href="#" onclick="settingsPage();return false">⚙️ Configurações</a>`:""}</nav></aside><main><div class="page-title"><h1>${title}</h1></div>${content}</main></div>`}
function renderApp(){dashboard()}
function logout(){localStorage.removeItem("sd_token");location.reload()}
async function dashboard(){const ts=await API.tickets();const counts=["ABERTO","EM_ATENDIMENTO","RESOLVIDO","FECHADO"].map(s=>[s,ts.filter(t=>t.status===s).length]);shell(`<div class="grid grid-4">${counts.map(([s,n])=>`<div class="card stat"><span class="muted">${s.replaceAll("_"," ")}</span><strong>${n}</strong></div>`).join("")}</div><div class="card" style="margin-top:18px"><h2>Tickets recentes</h2>${ticketTable(ts.slice(0,10))}</div>`,"Painel inicial")}
function ticketTable(ts){return `<div class="table-wrap"><table><thead><tr><th>Ticket</th><th>Assunto</th><th>Categoria</th><th>Urgência</th><th>Estado</th><th>Data</th></tr></thead><tbody>${ts.map(t=>`<tr><td><a href="#" onclick="viewTicket(${t.id});return false"><b>${esc(t.number)}</b></a></td><td>${esc(t.subject)}</td><td>${esc(t.category.name)}</td><td><span class="badge ${t.priority}">${t.priority}</span></td><td><span class="badge ${t.status}">${t.status.replaceAll("_"," ")}</span></td><td>${new Date(t.createdAt).toLocaleString("pt-MZ")}</td></tr>`).join("")||`<tr><td colspan="6" class="muted">Nenhum ticket encontrado.</td></tr>`}</tbody></table></div>`}
async function newTicket(){CATS=await API.request("/admin/categories").catch(()=>[]);shell(`<div class="card"><form id="ticketForm"><div class="grid grid-2"><div class="field"><label>Tipo <span class="required">*</span></label><select id="type" required><option value="">Selecione</option><option value="INCIDENTE">Incidente</option><option value="SOLICITACAO">Solicitação de Serviço</option><option value="RECLAMACAO">Reclamação / Sugestão</option><option value="OUTRO">Outro</option></select></div><div class="field"><label>Categoria <span class="required">*</span></label><select id="categoryId" required>${CATS.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("")}</select></div><div class="field"><label>Urgência <span class="required">*</span></label><select id="priority" required><option>BAIXA</option><option selected>MEDIA</option><option>ALTA</option><option>CRITICA</option></select></div><div class="field"><label>Departamento/sector</label><input id="department" value="${esc(ME.department)}"></div></div><div class="field"><label>Assunto <span class="required">*</span></label><input id="subject" required></div><div class="field"><label>Descrição detalhada <span class="required">*</span></label><textarea id="description" required></textarea></div><div class="grid grid-2"><div class="field"><label>Serviço/equipamento afetado</label><input id="affectedService"></div><div class="field" id="occWrap"><label>Data/hora da ocorrência</label><input id="occurrenceAt" type="datetime-local"></div></div><div id="printFields" class="card hidden"><h2>Dados de impressão</h2><div class="grid grid-2"><div class="field"><label>Tipo de documento</label><select id="documentType"><option>Teste</option><option>Exame</option><option>Documento Institucional</option><option>Outro</option></select></div><div class="field"><label>Disciplina/unidade curricular</label><input id="discipline"></div><div class="field"><label>Número de páginas</label><input id="pages" type="number" min="1"></div><div class="field"><label>Quantidade de cópias</label><input id="copies" type="number" min="1" value="1"></div><div class="field"><label>Formato</label><select id="printFormat"><option>Frente</option><option>Frente e verso</option><option>Cores</option><option>Preto e branco</option></select></div><div class="field"><label>Data/hora prevista</label><input id="scheduledAt" type="datetime-local"></div></div><div class="field"><label>Observações</label><textarea id="printObs"></textarea></div></div><button class="btn yellow">Submeter ticket</button></form></div>`,"Novo ticket");
document.querySelector("#categoryId").onchange=()=>{const c=CATS.find(x=>x.id==categoryId.value);printFields.classList.toggle("hidden",c?.name!=="Impressão e Documentos")};
document.querySelector("#type").onchange=()=>occWrap.classList.toggle("hidden",type.value!=="INCIDENTE");
document.querySelector("#ticketForm").onsubmit=async e=>{e.preventDefault();try{const cat=CATS.find(x=>x.id==categoryId.value);const data={type:type.value,categoryId:Number(categoryId.value),priority:priority.value,department:department.value,subject:subject.value,description:description.value,affectedService:affectedService.value,occurrenceAt:occurrenceAt.value||null};if(cat?.name==="Impressão e Documentos")data.print={documentType:documentType.value,discipline:discipline.value,pages:Number(pages.value),copies:Number(copies.value),format:printFormat.value,scheduledAt:scheduledAt.value,observations:printObs.value};const t=await API.createTicket(data);toast(`Ticket ${t.number} criado com sucesso.`,true);viewTicket(t.id)}catch(err){toast(err.message)}}}
async function myTickets(){const ts=await API.tickets();shell(`<div class="card">${ticketTable(ts)}</div>`,"Meus tickets")}
async function viewTicket(id){const t=await API.ticket(id);shell(`<div class="card"><div class="grid grid-2"><div><p class="muted">Número</p><h2>${esc(t.number)}</h2><p><b>Assunto:</b> ${esc(t.subject)}</p><p><b>Descrição:</b><br>${esc(t.description).replaceAll("\n","<br>")}</p><p><b>Categoria:</b> ${esc(t.category.name)}</p></div><div><p><b>Estado:</b> <span class="badge ${t.status}">${t.status}</span></p><p><b>Urgência:</b> <span class="badge ${t.priority}">${t.priority}</span></p><p><b>Solicitante:</b> ${esc(t.requester.name)}</p><p><b>Responsável:</b> ${esc(t.assignee?.name||"Não atribuído")}</p></div></div></div><div class="card" style="margin-top:18px"><h2>Histórico e respostas</h2>${t.comments.map(c=>`<div style="padding:12px 0;border-bottom:1px solid var(--border)"><b>${esc(c.author.name)}</b> <span class="muted">${new Date(c.createdAt).toLocaleString("pt-MZ")}</span><p>${esc(c.body)}</p></div>`).join("")||"<p class='muted'>Sem comentários.</p>"}<form id="commentForm" style="margin-top:16px"><textarea id="commentBody" required placeholder="Escreva uma resposta..."></textarea><button class="btn" style="margin-top:8px">Enviar</button></form></div>`,"Detalhe do ticket");
document.querySelector("#commentForm").onsubmit=async e=>{e.preventDefault();try{await API.comment(id,{body:commentBody.value});viewTicket(id)}catch(err){toast(err.message)}}}
async function manageTickets(){const ts=await API.tickets();shell(`<div class="card">${ticketTable(ts)}</div>`,"Gestão de tickets")}
async function adminDashboard(){const d=await API.admin("/dashboard");shell(`<div class="grid grid-4"><div class="card stat">Total<strong>${d.total}</strong></div><div class="card stat">Sem atribuição<strong>${d.unassigned}</strong></div><div class="card stat">SLA vencido<strong>${d.overdue}</strong></div><div class="card stat">Estados<strong>${d.statuses.length}</strong></div></div><div class="card" style="margin-top:18px"><h2>Exportação</h2><button class="btn yellow" onclick="exportCsv()">Exportar CSV</button></div>`,"Administração")}
async function exportCsv(){const r=await fetch("/api/admin/export/csv",{headers:{Authorization:`Bearer ${API.token}`}});const blob=await r.blob();const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="tickets.csv";a.click()}
async function usersPage(){const us=await API.admin("/users");shell(`<div class="card"><div class="actions"><button class="btn yellow" onclick="createUser()">Novo utilizador</button></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Departamento</th><th>Perfil</th><th>Ativo</th><th>Ações</th></tr></thead><tbody>${us.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc(u.department)}</td><td>${u.role}</td><td>${u.active?"Sim":"Não"}</td><td>${u.active?`<button class="btn danger" onclick="deactivateUser(${u.id})">Desativar</button>`:"—"}</td></tr>`).join("")}</tbody></table></div></div>`,"Utilizadores")}
async function createUser(){const name=prompt("Nome completo");if(!name)return;const email=prompt("E-mail");if(!email)return;const password=prompt("Palavra-passe (mínimo 8 caracteres)");if(!password)return;const department=prompt("Departamento/sector");if(!department)return;const role=prompt("Perfil: COLABORADOR, TECNICO ou ADMIN","COLABORADOR");try{await API.admin("/users",{method:"POST",body:JSON.stringify({name,email,password,department,role})});toast("Utilizador criado.",true);usersPage()}catch(e){toast(e.message)}}
async function deactivateUser(id){if(!confirm("Desativar este utilizador?"))return;try{await API.admin("/users/"+id,{method:"DELETE"});usersPage()}catch(e){toast(e.message)}}
async function categoriesPage(){const cs=await API.admin("/categories");shell(`<div class="card"><button class="btn yellow" onclick="createCategory()">Nova categoria</button><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Categoria</th><th>Ativa</th><th>Ação</th></tr></thead><tbody>${cs.map(c=>`<tr><td>${esc(c.name)}</td><td>${c.active?"Sim":"Não"}</td><td>${c.active?`<button class="btn danger" onclick="deleteCategory(${c.id})">Desativar</button>`:"—"}</td></tr>`).join("")}</tbody></table></div></div>`,"Categorias")}
async function createCategory(){const name=prompt("Nome da categoria");if(!name)return;try{await API.admin("/categories",{method:"POST",body:JSON.stringify({name})});categoriesPage()}catch(e){toast(e.message)}}
async function deleteCategory(id){if(!confirm("Desativar categoria?"))return;await API.admin("/categories/"+id,{method:"DELETE"});categoriesPage()}
async function settingsPage(){const s=await API.admin("/settings");const get=k=>s.find(x=>x.key===k)?.value||"";shell(`<div class="card"><form id="settingsForm"><div class="field"><label>LIMITE_PAGINAS</label><input id="limit" type="number" min="1" value="${esc(get("LIMITE_PAGINAS"))}"></div><div class="field"><label>ANTECEDENCIA_MINIMA_HORAS</label><input id="minHours" type="number" min="0" value="${esc(get("ANTECEDENCIA_MINIMA_HORAS"))}"></div><button class="btn yellow">Guardar configurações</button></form></div>`,"Configurações");settingsForm.onsubmit=async e=>{e.preventDefault();await API.admin("/settings",{method:"PUT",body:JSON.stringify({LIMITE_PAGINAS:limit.value,ANTECEDENCIA_MINIMA_HORAS:minHours.value})});toast("Configurações guardadas.",true)}}
boot();